name: AntiInstaBreak
main: dktapps\AntiInstaBreak\Main
version: 0.1.1
api: [3.0.0-ALPHA11, 3.0.0-ALPHA12]
load: POSTWORLD
author: dktapps
description: Times block-breaking in survival modes to prevent cheating.
